version: "3.9"

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    image: analytics_api:v1

    env_file:
      - .env.compose

    ports:
      - "8002:8000"

    
    volumes:
      - ./src:/code/src

    environment:
      - PYTHONPATH=/code/src


    command: uvicorn main:app --host 0.0.0.0 --port 8000 --reload

    develop:
      watch:
        - action: rebuild
          path: Dockerfile
        - action: rebuild
          path: requirements.txt
        - action: rebuild
          path: docker-compose.yml


  # postgresql+psycopg://time-user:time-password@db_service:5432/timescaledb
  db_service:
    image: timescale/timescaledb:latest-pg17
    environment:
      POSTGRES_USER: time-user
      POSTGRES_PASSWORD: time-password
      POSTGRES_DB: timescaledb
    ports:
      - "5432:5432"
    expose:
      - 5432
    volumes:
      - timescaledb_data:/var/lib/postgresql/data

volumes:
  timescaledb_data: